# flake8: noqa
from .env import ENV_BOOL, ENV_STR, ABS_PATH, ENV_SETTING

DEBUG = ENV_BOOL('DEBUG', False)
SECRET_KEY = ENV_STR('SECRET_KEY')
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + ABS_PATH(ENV_STR('SQLALCHEMY_DATABASE_URI'))
SQLALCHEMY_TRACK_MODIFICATIONS = True

MONGOALCHEMY_SERVER = ENV_STR('MONGOALCHEMY_SERVER')
MONGOALCHEMY_PORT = int(ENV_STR('MONGOALCHEMY_PORT'))
MONGOALCHEMY_DATABASE=ENV_STR('MONGOALCHEMY_DATABASE')

A_CONFIG_VALUE=ENV_STR('A_CONFIG_VALUE')
